services:
  - type: web
    name: attendance-system
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
